version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test_DB?schema=public
      - NODE_ENV=production
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: